[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@opengsn/=lib/gsn/packages/contracts/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config