/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Rps } from "./Rps";
export * as factories from "./factories";
export { Rps__factory } from "./factories/Rps__factory";
